name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: 
          - 15.8.0-alpine3.10
          - 15.8-alpine3.10
          - 15-alpine3.10
          - alpine3.10
          - current-alpine3.10
          - 15.8.0-alpine3.11
          - 15.8-alpine3.11
          - 15-alpine3.11
          - alpine3.11
          - current-alpine3.11
          - 15.8.0-alpine
          - 15.8-alpine
          - 15-alpine
          - alpine
          - current-alpine
          - 15.8.0-alpine3.12
          - 15.8-alpine3.12
          - 15-alpine3.12
          - alpine3.12
          - current-alpine3.12
          - 15.8.0-alpine3.13
          - 15.8-alpine3.13
          - 15-alpine3.13
          - alpine3.13
          - current-alpine3.13
          - 15.8.0-buster
          - 15.8-buster
          - 15-buster
          - buster
          - current-buster
          - 15.8.0-buster-slim
          - 15.8-buster-slim
          - 15-buster-slim
          - buster-slim
          - current-buster-slim
          - 15.8.0-stretch
          - 15.8-stretch
          - 15-stretch
          - stretch
          - current-stretch
          - 15.8.0
          - 15.8
          - 15
          - latest
          - current
          - 15.8.0-stretch-slim
          - 15.8-stretch-slim
          - 15-stretch-slim
          - stretch-slim
          - current-stretch-slim
          - 15.8.0-slim
          - 15.8-slim
          - 15-slim
          - slim
          - current-slim
          - 14.15.5-alpine3.10
          - 14.15-alpine3.10
          - 14-alpine3.10
          - fermium-alpine3.10
          - lts-alpine3.10
          - 14.15.5-alpine3.11
          - 14.15-alpine3.11
          - 14-alpine3.11
          - fermium-alpine3.11
          - lts-alpine3.11
          - 14.15.5-alpine
          - 14.15-alpine
          - 14-alpine
          - fermium-alpine
          - lts-alpine
          - 14.15.5-alpine3.12
          - 14.15-alpine3.12
          - 14-alpine3.12
          - fermium-alpine3.12
          - lts-alpine3.12
          - 14.15.5-alpine3.13
          - 14.15-alpine3.13
          - 14-alpine3.13
          - fermium-alpine3.13
          - lts-alpine3.13
          - 14.15.5-buster
          - 14.15-buster
          - 14-buster
          - fermium-buster
          - lts-buster
          - 14.15.5-buster-slim
          - 14.15-buster-slim
          - 14-buster-slim
          - fermium-buster-slim
          - lts-buster-slim
          - 14.15.5-stretch
          - 14.15-stretch
          - 14-stretch
          - fermium-stretch
          - lts-stretch
          - 14.15.5
          - 14.15
          - 14
          - fermium
          - lts
          - 14.15.5-stretch-slim
          - 14.15-stretch-slim
          - 14-stretch-slim
          - fermium-stretch-slim
          - lts-stretch-slim
          - 14.15.5-slim
          - 14.15-slim
          - 14-slim
          - fermium-slim
          - lts-slim
          - 12.20.2-alpine3.10
          - 12.20-alpine3.10
          - 12-alpine3.10
          - erbium-alpine3.10
          - 12.20.2-alpine3.11
          - 12.20-alpine3.11
          - 12-alpine3.11
          - erbium-alpine3.11
          - 12.20.2-alpine
          - 12.20-alpine
          - 12-alpine
          - erbium-alpine
          - 12.20.2-alpine3.12
          - 12.20-alpine3.12
          - 12-alpine3.12
          - erbium-alpine3.12
          - 12.20.2-buster
          - 12.20-buster
          - 12-buster
          - erbium-buster
          - 12.20.2-buster-slim
          - 12.20-buster-slim
          - 12-buster-slim
          - erbium-buster-slim
          - 12.20.2-stretch
          - 12.20-stretch
          - 12-stretch
          - erbium-stretch
          - 12.20.2
          - 12.20
          - 12
          - erbium
          - 12.20.2-stretch-slim
          - 12.20-stretch-slim
          - 12-stretch-slim
          - erbium-stretch-slim
          - 12.20.2-slim
          - 12.20-slim
          - 12-slim
          - erbium-slim
          - 10.23.3-alpine3.10
          - 10.23-alpine3.10
          - 10-alpine3.10
          - dubnium-alpine3.10
          - 10.23.3-alpine3.11
          - 10.23-alpine3.11
          - 10-alpine3.11
          - dubnium-alpine3.11
          - 10.23.3-alpine
          - 10.23-alpine
          - 10-alpine
          - dubnium-alpine
          - 10.23.3-buster
          - 10.23-buster
          - 10-buster
          - dubnium-buster
          - 10.23.3-buster-slim
          - 10.23-buster-slim
          - 10-buster-slim
          - dubnium-buster-slim
          - 10.23.3-stretch
          - 10.23-stretch
          - 10-stretch
          - dubnium-stretch
          - 10.23.3
          - 10.23
          - 10
          - dubnium
          - 10.23.3-stretch-slim
          - 10.23-stretch-slim
          - 10-stretch-slim
          - dubnium-stretch-slim
          - 10.23.3-slim
          - 10.23-slim
          - 10-slim
          - dubnium-slim

    steps:
      - name: Test environment variables
        env:
          NODE_VERSION: ${{ matrix.node }}
        run: echo $NODE_VERSION
        
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Set node version
        run: sed -i 's/\$NODE_VERSION/${{ matrix.node }}/' Dockerfile
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: eustatos/node-sass:${{ matrix.node }}
          build-args: |
            NODE_VERSION=10.23.3-alpine3.10
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
